name: jamaica_price_directory
description: "Jamaica Price Directory - Find the best prices across Jamaica"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^15.1.2
  
  # Network
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Camera & Image Processing (Updated versions)
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image: ^4.1.7
  
  # Location
  geolocator: ^14.0.1
  
  # Path utilities
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Permissions
  permission_handler: ^12.0.0+1
  
  # Additional camera-related packages for stability
  camera_platform_interface: ^2.7.1
  
  # Icons
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  crypto: ^3.0.6
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true